### ISSUE TITLE
Train_model is not working. Graph execution error:

### ISSUE THREAD

**Issue by adarsh3601** [astroai/starnet#2]
DNN library is not found.
	 [[{{node StarNet/conv1d/Conv1D}}]] [Op:__inference_train_function_1081]

This error is showing after successful loading of data, means_and_std.npz. Installing proper Tensrflow, keras and all. But training is not starting.

**Comment by teaghan** [comment]
Hi @adarsh3601 , I could not get the model to converge with the new tensorflow versions, so I have switched over to pytorch. Please install pytorch (`pip install torch torchvision`) and see the new notebooks [4_Train_Model_pytorch.ipynb](https://github.com/astroai/starnet/blob/master/4_Train_Model_pytorch.ipynb) and [5_Test_Model_pytorch.ipynb](https://github.com/astroai/starnet/blob/master/5_Test_Model_pytorch.ipynb)

**Comment by adarsh3601** [comment]
@teaghan  Thanks for the help it worked.

**Comment by teaghan** [comment]
@adarsh3601 You're very welcome. Good luck with your project!
